version: '3.8'
services: 
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: "jenkins"
    volumes: 
      -  './srv/data/jenkins_data:/jenkins_home'
      - './srv/data/jenkins:/var/jenkins_config'